# Brewfile
tap "homebrew/brew"

# cli
brew "gh"
brew "micro"
brew "neofetch"
brew "zsh"
brew "git"
brew "stow"

# casks
cask "alt-tab"
cask "bruno"
cask "grandperspective"
cask "helium-browser"
cask "jordanbaird-ice"
cask "linearmouse"
cask "localsend"
cask "raycast"
cask "tomatobar"
cask "utm"
cask "iina"
cask "keka"
cask "iterm2"
cask "spotify"
